(function (global) {
    var blacklist = [
        "extensions.hackbar.selected_c",
        "extensions.hackbar.selected_t",
        "extensions.hackbar.selected_tc",
        "extensions.hackbar.selected_g",
        "extensions.hackbar.selected_tb",
        "extensions.hackbar.selected_lb",
        "extensions.hackbar.selected_sb",
        "extensions.hackbar.firstrun",
        "extensions.hackbar.Show Update",
        "extensions.hackbar.starts",
        "extensions.hackbar.Enable notifications",
        "extensions.hackbar.Always notify",
        "extensions.hackbar.Release notes",
        "app.download.available",
        "app.update.available.date",
        "app.update.name.version",
        "app.update.status",
        "extensions.hackbar.visibility.SQL BASIC",
        "extensions.hackbar.visibility.UNION BASED",
        "extensions.hackbar.visibility.OUT FILE",
        "extensions.hackbar.visibility.WAF BASED",
        "extensions.hackbar.visibility.CUSTOM",
        "extensions.hackbar.visibility.ERROR/DOUBLE QUERY",
        "extensions.hackbar.visibility.TOOLS",
        "extensions.hackbar.visibility.WAF BYPASS",
        "extensions.hackbar.visibility.LDAP FUZZ",
        "extensions.hackbar.visibility.ENCODING",
        "extensions.hackbar.visibility.0xHTML",
        "extensions.hackbar.visibility.ENCRYPTION",
        "extensions.hackbar.visibility.OTHERS",
        "extensions.hackbar.visibility.XSS",
        "extensions.hackbar.visibility.LFI",
        "extensions.hackbar.visibility.LINKS"
    ];
    /*
    var backupstyle = [
        "addons.style.enabled",
        "extensions.hackbar.selected_c",
        "extensions.hackbar.selected_t",
        "extensions.hackbar.selected_tc",
        "extensions.hackbar.selected_g",
        "extensions.hackbar.selected_tb",
        "extensions.hackbar.selected_lb",
        "extensions.hackbar.selected_sb",
        "extensions.hackbar.firstrun",
        "extensions.hackbar.Show Update",
        "extensions.hackbar.starts",
        "extensions.hackbar.Enable notifications",
        "extensions.hackbar.Always notify",
        "extensions.hackbar.Release notes",
        "app.download.available",
        "app.update.available.date",
        "app.update.name.version",
        "app.update.status",
        "extensions.hackbar.visibility.SQL BASIC",
        "extensions.hackbar.visibility.UNION BASED",
        "extensions.hackbar.visibility.OUT FILE",
        "extensions.hackbar.visibility.WAF BASED",
        "extensions.hackbar.visibility.CUSTOM",
        "extensions.hackbar.visibility.ERROR/DOUBLE QUERY",
        "extensions.hackbar.visibility.TOOLS",
        "extensions.hackbar.visibility.WAF BYPASS",
        "extensions.hackbar.visibility.LDAP FUZZ",
        "extensions.hackbar.visibility.ENCODING",
        "extensions.hackbar.visibility.0xHTML",
        "extensions.hackbar.visibility.ENCRYPTION",
        "extensions.hackbar.visibility.OTHERS",
        "extensions.hackbar.visibility.XSS",
        "extensions.hackbar.visibility.LFI",
        "extensions.hackbar.visibility.LINKS",
        "extensions.hackbar.Dios.Dios 1",
        "extensions.hackbar.Dios.Dios 2",
        "extensions.hackbar.Dios.Dios 3",
        "extensions.hackbar.Dios.Dios 4",
        "extensions.hackbar.Dios.Dios 5",
        "extensions.hackbar.Dios.Dios 6",
        "extensions.hackbar.Dios.Dios 7",
        "extensions.hackbar.Dios.Dios 8",
        "extensions.hackbar.Dios.Dios 9",
        "extensions.hackbar.Dios.Dios 10",
        "extensions.hackbar.query.query 1",
        "extensions.hackbar.query.query 2",
        "extensions.hackbar.query.query 3",
        "extensions.hackbar.query.query 4",
        "extensions.hackbar.query.query 5",
        "extensions.hackbar.query.query 6",
        "extensions.hackbar.query.query 7",
        "extensions.hackbar.query.query 8",
        "extensions.hackbar.query.query 9",
        "extensions.hackbar.query.query 10",
        "extensions.hackbar.Name Dios.Dios 1",
        "extensions.hackbar.Name Dios.Dios 2",
        "extensions.hackbar.Name Dios.Dios 3",
        "extensions.hackbar.Name Dios.Dios 4",
        "extensions.hackbar.Name Dios.Dios 5",
        "extensions.hackbar.Name Dios.Dios 6",
        "extensions.hackbar.Name Dios.Dios 7",
        "extensions.hackbar.Name Dios.Dios 8",
        "extensions.hackbar.Name Dios.Dios 9",
        "extensions.hackbar.Name Dios.Dios 10",
        "extensions.hackbar.Name Query.query 1",
        "extensions.hackbar.Name Query.query 2",
        "extensions.hackbar.Name Query.query 3",
        "extensions.hackbar.Name Query.query 4",
        "extensions.hackbar.Name Query.query 5",
        "extensions.hackbar.Name Query.query 6",
        "extensions.hackbar.Name Query.query 7",
        "extensions.hackbar.Name Query.query 8",
        "extensions.hackbar.Name Query.query 9",
        "extensions.hackbar.Name Query.query 10",
        "extensions.hackbar.XSS.XSS 1",
        "extensions.hackbar.XSS.XSS 2",
        "extensions.hackbar.XSS.XSS 3",
        "extensions.hackbar.XSS.XSS 4",
        "extensions.hackbar.XSS.XSS 5",
        "extensions.hackbar.XSS.XSS 6",
        "extensions.hackbar.XSS.XSS 7",
        "extensions.hackbar.XSS.XSS 8",
        "extensions.hackbar.XSS.XSS 9",
        "extensions.hackbar.XSS.XSS 10"
    ];
    */
    // Make blacklist a global variable
    global.blacklist = blacklist;
    //global.backupstyle = backupstyle;
}(this));