pref("extensions.{F5DDF39C-9293-4d5e-9AA8-E04E6DD5E9B4}.description", "chrome://hackbar/locale/hackbar.properties");
pref("extensions.jsswitch.showinmenu", false);
pref("extensions.jsswitch.showinstatusbar", false);
pref("extensions.hackbar.visibility.SQL BASIC",false);
pref("extensions.hackbar.visibility.UNION BASED",false);	
pref("extensions.hackbar.visibility.OUT FILE",false);
pref("extensions.hackbar.visibility.WAF BASED",false);				
pref("extensions.hackbar.visibility.CUSTOM",false);					
pref("extensions.hackbar.visibility.ERROR/DOUBLE QUERY",false);		
pref("extensions.hackbar.visibility.TOOLS",false);					
pref("extensions.hackbar.visibility.WAF BYPASS",false);			
pref("extensions.hackbar.visibility.LDAP FUZZ",false);				
pref("extensions.hackbar.visibility.ENCODING",false);				
pref("extensions.hackbar.visibility.0xHTML",false);					
pref("extensions.hackbar.visibility.ENCRYPTION",false);				
pref("extensions.hackbar.visibility.OTHERS",false);					
pref("extensions.hackbar.visibility.XSS",false);					
pref("extensions.hackbar.visibility.LFI",false);					
pref("extensions.hackbar.visibility.LINKS",false);				
pref("addons.style.enabled",false);
//
pref("extensions.hackbar.firstrun", false);
//
pref("extensions.hackbar.Arrow.BASE64ArrowLeft","chrome://hackbar/skin/ArrowLeft3.png");
pref("extensions.hackbar.Arrow.BASE64ArrowRight","chrome://hackbar/skin/ArrowRight3.png");
pref("extensions.hackbar.Arrow.BASE64Spacer","chrome://hackbar/skin/ArrowRight3.png");
pref("extensions.hackbar.Arrow.BINARYArrowLeft","chrome://hackbar/skin/ArrowLeft3.png");
pref("extensions.hackbar.Arrow.BINARYArrowRight","chrome://hackbar/skin/ArrowRight3.png");
pref("extensions.hackbar.Arrow.HexArrowLeft","chrome://hackbar/skin/ArrowLeft3.png");
pref("extensions.hackbar.Arrow.HexArrowRight","chrome://hackbar/skin/ArrowRight3.png");
pref("extensions.hackbar.Arrow.Replace","chrome://hackbar/skin/ArrowRight3.png");
pref("extensions.hackbar.Arrow.URLArrowLeft","chrome://hackbar/skin/ArrowLeft3.png");
pref("extensions.hackbar.Arrow.URLArrowRight","chrome://hackbar/skin/ArrowRight3.png");
pref("extensions.hackbar.ExcuteURL.ExcuteIcon","");
pref("extensions.hackbar.SplitURL.SplitIcon","");
pref("extensions.hackbar.loadURL.LoadIcon","");
//
pref("extensions.hackbar.SQL BASIC","");
pref("extensions.hackbar.UNION BASED","");
pref("extensions.hackbar.OUT FILE","");
pref("extensions.hackbar.WAF BASED","");
pref("extensions.hackbar.CUSTOM","");
pref("extensions.hackbar.ERROR/DOUBLE QUERY","");
pref("extensions.hackbar.TOOLS","");
pref("extensions.hackbar.WAF BYPASS","");
pref("extensions.hackbar.LDAP FUZZ","");
pref("extensions.hackbar.ENCODING","");
pref("extensions.hackbar.0xHTML","");
pref("extensions.hackbar.ENCRYPTION","");
pref("extensions.hackbar.OTHERS","");
pref("extensions.hackbar.XSS","");
pref("extensions.hackbar.LFI","");
pref("extensions.hackbar.LINKS","");
//Dios
pref("extensions.hackbar.Dios.Dios 1",  "Dios 1");
pref("extensions.hackbar.Dios.Dios 2",  "Dios 2");
pref("extensions.hackbar.Dios.Dios 3",  "Dios 3");
pref("extensions.hackbar.Dios.Dios 4",  "DIos 4");
pref("extensions.hackbar.Dios.Dios 5",  "Dios 5");
pref("extensions.hackbar.Dios.Dios 6",  "Dios 6");
pref("extensions.hackbar.Dios.Dios 7",  "Dios 7");
pref("extensions.hackbar.Dios.Dios 8",  "Dios 8");
pref("extensions.hackbar.Dios.Dios 9",  "Dios 9");
pref("extensions.hackbar.Dios.Dios 10", "Dios 10");
//Query
pref("extensions.hackbar.query.query 1",  "query 1");
pref("extensions.hackbar.query.query 2",  "query 2");
pref("extensions.hackbar.query.query 3",  "query 3");
pref("extensions.hackbar.query.query 4",  "query 4");
pref("extensions.hackbar.query.query 5",  "query 5");
pref("extensions.hackbar.query.query 6",  "query 6");
pref("extensions.hackbar.query.query 7",  "query 7");
pref("extensions.hackbar.query.query 8",  "query 8");
pref("extensions.hackbar.query.query 9",  "query 9");
pref("extensions.hackbar.query.query 10", "query 10");
pref("extensions.hackbar.query.query 11", "query 11");
pref("extensions.hackbar.query.query 12", "query 12");
pref("extensions.hackbar.query.query 13", "query 13");
pref("extensions.hackbar.query.query 14", "query 14");
pref("extensions.hackbar.query.query 15", "query 15");
//Name Dios
pref("extensions.hackbar.Name Dios.Dios 1",  "Dios 1");
pref("extensions.hackbar.Name Dios.Dios 2",  "Dios 2");
pref("extensions.hackbar.Name Dios.Dios 3",  "Dios 3");
pref("extensions.hackbar.Name Dios.Dios 4",  "DIos 4");
pref("extensions.hackbar.Name Dios.Dios 5",  "Dios 5");
pref("extensions.hackbar.Name Dios.Dios 6",  "Dios 6");
pref("extensions.hackbar.Name Dios.Dios 7",  "Dios 7");
pref("extensions.hackbar.Name Dios.Dios 8",  "Dios 8");
pref("extensions.hackbar.Name Dios.Dios 9",  "Dios 9");
pref("extensions.hackbar.Name Dios.Dios 10", "Dios 10");
//Name Query
pref("extensions.hackbar.Name Query.query 1",  "query 1");
pref("extensions.hackbar.Name Query.query 2",  "query 2");
pref("extensions.hackbar.Name Query.query 3",  "query 3");
pref("extensions.hackbar.Name Query.query 4",  "query 4");
pref("extensions.hackbar.Name Query.query 5",  "query 5");
pref("extensions.hackbar.Name Query.query 6",  "query 6");
pref("extensions.hackbar.Name Query.query 7",  "query 7");
pref("extensions.hackbar.Name Query.query 8",  "query 8");
pref("extensions.hackbar.Name Query.query 9",  "query 9");
pref("extensions.hackbar.Name Query.query 10", "query 10");
pref("extensions.hackbar.Name Query.query 11", "query 11");
pref("extensions.hackbar.Name Query.query 12", "query 12");
pref("extensions.hackbar.Name Query.query 13", "query 13");
pref("extensions.hackbar.Name Query.query 14", "query 14");
pref("extensions.hackbar.Name Query.query 15", "query 15");
//XSS
pref("extensions.hackbar.XSS.XSS 1",  "XSS 1");
pref("extensions.hackbar.XSS.XSS 2",  "XSS 2");
pref("extensions.hackbar.XSS.XSS 3",  "XSS 3");
pref("extensions.hackbar.XSS.XSS 4",  "XSS 4");
pref("extensions.hackbar.XSS.XSS 5",  "XSS 5");
pref("extensions.hackbar.XSS.XSS 6",  "XSS 6");
pref("extensions.hackbar.XSS.XSS 7",  "XSS 7");
pref("extensions.hackbar.XSS.XSS 8",  "XSS 8");
pref("extensions.hackbar.XSS.XSS 9",  "XSS 9");
pref("extensions.hackbar.XSS.XSS 10", "XSS 10");
//hackBarTargetUrl
pref("extensions.hackbar.hackBarTargetUrl.color",  "#00ff00");
pref("extensions.hackbar.hackBarTargetUrl.backgroundColor",  "#000000");
pref("extensions.hackbar.hackBarTargetUrl.borderTop",  "#00ff00");
pref("extensions.hackbar.hackBarTargetUrl.borderLeft",  "#00ff00");
pref("extensions.hackbar.hackBarTargetUrl.borderBottom",  "#00ff00");
pref("extensions.hackbar.hackBarTargetUrl.borderRight",  "#00ff00");
pref("extensions.hackbar.hackBarTargetUrl.borderSize", "3");
pref("extensions.hackbar.hackBarTargetUrl.borderRadius",  "10");
pref("extensions.hackbar.hackBarTargetUrl.fontSize",  "15");
pref("extensions.hackbar.hackBarTargetUrl.font-family",  "Arial");
pref("extensions.hackbar.hackBarTargetUrl.bold",false);
pref("extensions.hackbar.hackBarTargetUrl.italic",false);
pref("extensions.hackbar.hackBarTargetUrl.font-weight","none");
pref("extensions.hackbar.hackBarTargetUrl.font-style","none");
//hackBarTargetUrlReferrerField
pref("extensions.hackbar.hackBarTargetUrlReferrerField.color",  "#00ff00");
pref("extensions.hackbar.hackBarTargetUrlReferrerField.backgroundColor",  "#000000");
pref("extensions.hackbar.hackBarTargetUrlReferrerField.borderTop",  "#00ff00");
pref("extensions.hackbar.hackBarTargetUrlReferrerField.borderLeft",  "#00ff00");
pref("extensions.hackbar.hackBarTargetUrlReferrerField.borderBottom",  "#00ff00");
pref("extensions.hackbar.hackBarTargetUrlReferrerField.borderRight",  "#00ff00");
pref("extensions.hackbar.hackBarTargetUrlReferrerField.borderSize", "3");
pref("extensions.hackbar.hackBarTargetUrlReferrerField.borderRadius",  "10");
pref("extensions.hackbar.hackBarTargetUrlReferrerField.fontSize", "15");
pref("extensions.hackbar.hackBarTargetUrlReferrerField.font-family",  "Arial");
pref("extensions.hackbar.hackBarTargetUrlReferrerField.bold",false);
pref("extensions.hackbar.hackBarTargetUrlReferrerField.italic",false);
pref("extensions.hackbar.hackBarTargetUrlReferrerField.font-weight","none");
pref("extensions.hackbar.hackBarTargetUrlReferrerField.font-style","none");
//hackBarTargetUrlPostField
pref("extensions.hackbar.hackBarTargetUrlPostField.color",  "#00ff00");
pref("extensions.hackbar.hackBarTargetUrlPostField.backgroundColor",  "#000000");
pref("extensions.hackbar.hackBarTargetUrlPostField.borderTop",  "#00ff00");
pref("extensions.hackbar.hackBarTargetUrlPostField.borderLeft",  "#00ff00");
pref("extensions.hackbar.hackBarTargetUrlPostField.borderBottom",  "#00ff00");
pref("extensions.hackbar.hackBarTargetUrlPostField.borderRight",  "#00ff00");
pref("extensions.hackbar.hackBarTargetUrlPostField.borderSize", "3");
pref("extensions.hackbar.hackBarTargetUrlPostField.borderRadius",  "10");
pref("extensions.hackbar.hackBarTargetUrlPostField.fontSize",  "15");
pref("extensions.hackbar.hackBarTargetUrlPostField.font-family",  "Arial");
pref("extensions.hackbar.hackBarTargetUrlPostField.bold",false);
pref("extensions.hackbar.hackBarTargetUrlPostField.italic",false);
pref("extensions.hackbar.hackBarTargetUrlPostField.font-weight","none");
pref("extensions.hackbar.hackBarTargetUrlPostField.font-style","none");
//toolbar
pref("extensions.hackbar.toolbar.backgroundColor",  "#000000");
pref("extensions.hackbar.toolbar.borderTop",  "#00ff00");
pref("extensions.hackbar.toolbar.borderLeft",  "#00ff00");
pref("extensions.hackbar.toolbar.borderBottom",  "#00ff00");
pref("extensions.hackbar.toolbar.borderRight",  "#00ff00");
pref("extensions.hackbar.toolbar.borderSize", "3");
pref("extensions.hackbar.toolbar.borderRadius",  "10");
//menupopup
pref("extensions.hackbar.menupopup.backgroundColor","#000000");
pref("extensions.hackbar.menupopup.borderTop","#00ff00");
pref("extensions.hackbar.menupopup.borderLeft","#00ff00");
pref("extensions.hackbar.menupopup.borderBottom","#00ff00");
pref("extensions.hackbar.menupopup.borderRight","#00ff00");
pref("extensions.hackbar.menupopup.borderSize","3");
pref("extensions.hackbar.menupopup.borderRadius","10");
pref("extensions.hackbar.menupopup.opacity","0.9");
//menuitem
pref("extensions.hackbar.menuitem.color","#ff0000");
pref("extensions.hackbar.menuitem.font-family","Arial");
pref("extensions.hackbar.menuitem.fontSize","12");
pref("extensions.hackbar.menuitem.bold",false);
pref("extensions.hackbar.menuitem.italic",false);
pref("extensions.hackbar.menuitem.font-weight","none");
pref("extensions.hackbar.menuitem.font-style","none");
//String to replace 
pref("extensions.hackbar.toolbarbutton.color","#ff0000");
pref("extensions.hackbar.toolbarbutton.font-family","Arial");
pref("extensions.hackbar.toolbarbutton.fontSize","12");
pref("extensions.hackbar.toolbarbutton.bold",false);
pref("extensions.hackbar.toolbarbutton.italic",false);
pref("extensions.hackbar.toolbarbutton.font-weight","none");
pref("extensions.hackbar.toolbarbutton.font-style","none");

pref("extensions.hackbar.rstring1.color","#00ff00");
pref("extensions.hackbar.rstring1.backgroundColor","#000000");
pref("extensions.hackbar.rstring1.borderTop","#00ff00");
pref("extensions.hackbar.rstring1.borderLeft","#00ff00");
pref("extensions.hackbar.rstring1.borderBottom","#00ff00");
pref("extensions.hackbar.rstring1.borderRight","#00ff00");
pref("extensions.hackbar.rstring1.borderSize","1");
pref("extensions.hackbar.rstring1.borderRadius","0");
pref("extensions.hackbar.rstring1.fontSize","12");
pref("extensions.hackbar.rstring1.font-family","Arial");
pref("extensions.hackbar.rstring1.bold",false);
pref("extensions.hackbar.rstring1.italic",false);
pref("extensions.hackbar.rstring1.font-weight","none");
pref("extensions.hackbar.rstring1.font-style","none");
//String to replace 
pref("extensions.hackbar.rstring2.color","#00ff00");
pref("extensions.hackbar.rstring2.backgroundColor","#000000");
pref("extensions.hackbar.rstring2.borderTop","#00ff00");
pref("extensions.hackbar.rstring2.borderLeft","#00ff00");
pref("extensions.hackbar.rstring2.borderBottom","#00ff00");
pref("extensions.hackbar.rstring2.borderRight","#00ff00");
pref("extensions.hackbar.rstring2.borderSize","1");
pref("extensions.hackbar.rstring2.borderRadius","0");
pref("extensions.hackbar.rstring2.fontSize","12");
pref("extensions.hackbar.rstring2.font-family","Arial");
pref("extensions.hackbar.rstring2.bold",false);
pref("extensions.hackbar.rstring2.italic",false);
pref("extensions.hackbar.rstring2.font-weight","none");
pref("extensions.hackbar.rstring2.font-style","none");
//Selection
pref("extensions.hackbar.Selection.color",  "#00ff00");
pref("extensions.hackbar.Selection.backgroundColor",  "#000000");
pref("extensions.hackbar.Selection.borderTop",  "#00ff00");
pref("extensions.hackbar.Selection.borderLeft",  "#00ff00");
pref("extensions.hackbar.Selection.borderBottom",  "#00ff00");
pref("extensions.hackbar.Selection.borderRight",  "#00ff00");
pref("extensions.hackbar.Selection.borderSize", "3");
pref("extensions.hackbar.Selection.borderRadius",  "10");
pref("extensions.hackbar.Selection.fontSize",  "15");
pref("extensions.hackbar.Selection.font-family",  "Arial");
pref("extensions.hackbar.Selection.bold",false);
pref("extensions.hackbar.Selection.italic",false);
pref("extensions.hackbar.Selection.font-weight","none");
pref("extensions.hackbar.Selection.font-style","none");
//loadURL
pref("extensions.hackbar.loadURL.color",  "#00ff00");
pref("extensions.hackbar.loadURL.backgroundColor",  "#000000");
pref("extensions.hackbar.loadURL.borderTop",  "#00ff00");
pref("extensions.hackbar.loadURL.borderLeft",  "#00ff00");
pref("extensions.hackbar.loadURL.borderBottom",  "#00ff00");
pref("extensions.hackbar.loadURL.borderRight",  "#00ff00");
pref("extensions.hackbar.loadURL.borderSize", "3");
pref("extensions.hackbar.loadURL.borderRadius",  "10");
pref("extensions.hackbar.loadURL.fontSize",  "15");
pref("extensions.hackbar.loadURL.font-family",  "Arial");
pref("extensions.hackbar.loadURL.bold",false);
pref("extensions.hackbar.loadURL.italic",false);
pref("extensions.hackbar.loadURL.font-weight","none");
pref("extensions.hackbar.loadURL.font-style","none");
//SplitURL
pref("extensions.hackbar.SplitURL.color",  "#00ff00");
pref("extensions.hackbar.SplitURL.backgroundColor",  "#000000");
pref("extensions.hackbar.SplitURL.borderTop",  "#00ff00");
pref("extensions.hackbar.SplitURL.borderLeft",  "#00ff00");
pref("extensions.hackbar.SplitURL.borderBottom",  "#00ff00");
pref("extensions.hackbar.SplitURL.borderRight",  "#00ff00");
pref("extensions.hackbar.SplitURL.borderSize", "3");
pref("extensions.hackbar.SplitURL.borderRadius",  "10");
pref("extensions.hackbar.SplitURL.fontSize",  "15");
pref("extensions.hackbar.SplitURL.font-family",  "Arial");
pref("extensions.hackbar.SplitURL.bold",false);
pref("extensions.hackbar.SplitURL.italic",false);
pref("extensions.hackbar.SplitURL.font-weight","none");
pref("extensions.hackbar.SplitURL.font-style","none");
//ExcuteURL
pref("extensions.hackbar.ExcuteURL.color",  "#00ff00");
pref("extensions.hackbar.ExcuteURL.backgroundColor",  "#000000");
pref("extensions.hackbar.ExcuteURL.borderTop",  "#00ff00");
pref("extensions.hackbar.ExcuteURL.borderLeft",  "#00ff00");
pref("extensions.hackbar.ExcuteURL.borderBottom",  "#00ff00");
pref("extensions.hackbar.ExcuteURL.borderRight",  "#00ff00");
pref("extensions.hackbar.ExcuteURL.borderSize", "3");
pref("extensions.hackbar.ExcuteURL.borderRadius",  "10");
pref("extensions.hackbar.ExcuteURL.fontSize",  "15");
pref("extensions.hackbar.ExcuteURL.font-family",  "Arial");
pref("extensions.hackbar.ExcuteURL.bold",false);
pref("extensions.hackbar.ExcuteURL.italic",false);
pref("extensions.hackbar.ExcuteURL.font-weight","none");
pref("extensions.hackbar.ExcuteURL.font-style","none");